sudo: required
language: node_js
node_js: 8.0

cache:
 directories:
   - node_modules

install:
- npm install
- bower install

before_script:
- polymer lint --rules polymer-2 --input *.html
- eslint . --ext js,html --ignore-path .gitignore

addons:
 firefox: latest
 apt:
   sources:
     - google-chrome
   packages:
     - google-chrome-stable

script:
- xvfb-run polymer test

dist: trusty
